language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=test/buildtest.cpp

install:
    - pip install -U platformio
# Install ArduinoJson and Timezone by ID:
    - platformio lib -g install 64 76

script:
    - platformio ci --lib="." --board=esp12e --board=adafruit_feather_m0 
test/buildtest.cpp
